# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rspec", "~> 3.13"
gem "sinatra", "~> 4.1"
gem "rackup", "~> 2.2"
gem "puma", "~> 6.6"
gem "sinatra-contrib", "~> 4.1"
gem "rack-test", "~> 2.2"
gem "rack", "~> 3.1"
gem "webmock", "~> 3.25"

gem "pry", "~> 0.15.2"
