# frozen_string_literal: true

source "https://rubygems.org"

gem "puma", "~> 6.6"
gem "rack", "~> 3.1"
gem "rack-test", "~> 2.2"
gem "rackup", "~> 2.2"
gem "rspec", "~> 3.13"
gem "sinatra", "~> 4.1"
gem "sinatra-contrib", "~> 4.1"
gem "sqlite3", "~> 2.7"

gem "simplecov", "~> 0.22.0"
